"use client";
import {FormEvent,useState} from "react";
import Link from "next/link";
import BreakingManager from "./BreakingManager";
import TeamManager from "./TeamManager";
import AudioHighlightsManager from "./AudioHighlightsManager";
import NewsManager from "./NewsManager";
type Props={user:{name:string,email:string};roleLabel:string;allowed:string[];signout:string};
const nav=["डैशबोर्ड","समाचार","नई पोस्ट","श्रेणियाँ","रिपोर्टर","ब्रेकिंग न्यूज़","ऑडियो हाइलाइट्स","विज्ञापन","मीडिया लाइब्रेरी","टिप्पणियाँ","टीम और भूमिकाएँ"];
const baseArticles=[
 {title:"प्रदेश के छोटे शहरों में युवाओं के लिए खुल रहे रोजगार के द्वार",category:"मध्य प्रदेश",author:"राहुल राठौर",status:"प्रकाशित",views:"18.4K",date:"24 अगस्त, 10:32"},
 {title:"राष्ट्रीय प्रतियोगिता में युवा खिलाड़ियों ने रचा इतिहास",category:"खेल",author:"संदीप शर्मा",status:"प्रकाशित",views:"12.1K",date:"24 अगस्त, 09:18"},
 {title:"डिजिटल कक्षाओं से गांव के विद्यार्थियों को मिली नई दिशा",category:"शिक्षा",author:"न्यूज़ डेस्क",status:"ड्राफ्ट",views:"—",date:"23 अगस्त, 18:42"},
];
export default function AdminDashboard({user,roleLabel,allowed,signout}:Props){const[tab,setTab]=useState("डैशबोर्ड");const[articles,setArticles]=useState(baseArticles);const[breaking,setBreaking]=useState("राष्ट्रीय राजमार्ग परियोजना को मिली मंजूरी");const[toast,setToast]=useState("");const[menu,setMenu]=useState(false);function notify(x:string){setToast(x);setTimeout(()=>setToast(""),2200)}return <div className="adminShell">
 <aside className={`adminNav ${menu?"open":""}`}><Link className="adminBrand" href="/"><b>NEWS<span>24x7</span></b><small>ADMIN DESK</small></Link><nav>{nav.filter(x=>allowed.includes(x)).map((x,i)=><button key={x} className={tab===x?"active":""} onClick={()=>{setTab(x);setMenu(false)}}><i>{["▦","▤","＋","◫","♙","⚡","▣","▧","◌","♜"][i]}</i>{x}{x==="टिप्पणियाँ"&&<em>12</em>}</button>)}</nav><div className="navBottom">{allowed.includes("सेटिंग्स")&&<button onClick={()=>setTab("सेटिंग्स")}>⚙ सेटिंग्स</button>}<a href={signout}>↪ साइन आउट</a></div></aside>
 <main className="adminMain"><header><div><button className="mobileMenu" onClick={()=>setMenu(!menu)}>☰</button><h1>{tab}</h1><p>नमस्कार, {user.name.split(" ")[0]} — न्यूज़रूम में आपका स्वागत है।</p></div><div className="adminActions"><button className="bell" onClick={()=>notify("कोई नई सूचना नहीं")}>♢<i/></button><div className="avatar">{user.name.slice(0,1).toUpperCase()}</div><div><b>{user.name}</b><small>{roleLabel}</small></div></div></header>
 {tab==="डैशबोर्ड"?<Dashboard articles={articles} breaking={breaking} setBreaking={setBreaking} setTab={setTab} notify={notify}/>:<Workspace tab={tab} setTab={setTab} articles={articles} setArticles={setArticles} notify={notify} currentEmail={user.email}/>} 
 </main>{toast&&<div className="adminToast">✓ {toast}</div>}</div>}

function Dashboard({articles,breaking,setBreaking,setTab}:{articles:typeof baseArticles;breaking:string;setBreaking:(x:string)=>void;setTab:(x:string)=>void;notify:(x:string)=>void}){return <><section className="statsGrid">{[["आज के व्यूज़","48,294","↑ 12.4%","◉"],["प्रकाशित खबरें","2,048","+8 आज","▤"],["कुल रिपोर्टर","32","28 सक्रिय","♙"],["विज्ञापन आय","₹84,500","इस माह","▣"]].map(s=><article key={s[0]}><div className="statIcon">{s[3]}</div><span>{s[0]}</span><strong>{s[1]}</strong><small>{s[2]}</small></article>)}</section><section className="breakingEditor"><div><span>⚡ लाइव ब्रेकिंग न्यूज़</span><p>कई हेडलाइन जोड़ें और नियंत्रित करें</p></div><input value={breaking} onChange={e=>setBreaking(e.target.value)} readOnly/><button onClick={()=>setTab("ब्रेकिंग न्यूज़")}>सभी मैनेज करें</button><label><input type="checkbox" defaultChecked disabled/> लाइव</label></section><section className="adminGrid"><ArticleTable articles={articles} setTab={setTab}/><aside className="adminSide"><div className="panel quick"><h2>त्वरित कार्य</h2>{[["＋","नई पोस्ट","लेख बनाएं और प्रकाशित करें"],["▧","मीडिया लाइब्रेरी","फोटो और वीडियो जोड़ें"],["♙","रिपोर्टर","नई टीम सदस्य प्रोफाइल"],["▣","विज्ञापन","नया विज्ञापन अभियान"]].map(x=><button key={x[1]} onClick={()=>setTab(x[1])}><i>{x[0]}</i><span><b>{x[1]}</b><small>{x[2]}</small></span><em>›</em></button>)}</div><div className="panel activity"><h2>हाल की गतिविधि</h2>{["राहुल ने खबर प्रकाशित की","संदीप ने ड्राफ्ट अपडेट किया","विज्ञापन अभियान सक्रिय हुआ"].map((x,i)=><div key={x}><i>{["र","स","वि"][i]}</i><p><b>{x}</b><small>{i+1} घंटे पहले</small></p></div>)}</div></aside></section></>}
function ArticleTable({articles,setTab}:{articles:typeof baseArticles;setTab:(x:string)=>void}){return <div className="panel"><div className="panelHead"><div><h2>हाल की खबरें</h2><p>समाचारों को संपादित और प्रकाशित करें</p></div><button className="primary" onClick={()=>setTab("नई पोस्ट")}>＋ नई खबर लिखें</button></div><div className="tableWrap"><table><thead><tr><th>शीर्षक</th><th>श्रेणी</th><th>लेखक</th><th>स्थिति</th><th>व्यूज़</th><th>अपडेट</th></tr></thead><tbody>{articles.map(a=><tr key={a.title}><td><b>{a.title}</b></td><td><span className="pill">{a.category}</span></td><td>{a.author}</td><td><span className={`status ${a.status}`}>● {a.status}</span></td><td>{a.views}</td><td>{a.date}</td></tr>)}</tbody></table></div><button className="viewAll" onClick={()=>setTab("समाचार")}>सभी समाचार देखें →</button></div>}

function Workspace({tab,setTab,articles,setArticles,notify,currentEmail}:{tab:string;setTab:(x:string)=>void;articles:typeof baseArticles;setArticles:(x:typeof baseArticles)=>void;notify:(x:string)=>void;currentEmail:string}){const[cats,setCats]=useState(["देश","मध्य प्रदेश","राजनीति","अपराध","कारोबार","शिक्षा","खेल"]);const[reporters,setReporters]=useState(["राहुल राठौर","संदीप शर्मा","प्रिया शर्मा"]);const[assets,setAssets]=useState(["राज्य-विकास.jpg","खेल-महोत्सव.jpg","शिक्षा-अभियान.mp4"]);function submit(e:FormEvent<HTMLFormElement>,type:string){e.preventDefault();const f=new FormData(e.currentTarget);if(type==="article"){const title=String(f.get("title"));setArticles([{title,category:String(f.get("category")),author:"न्यूज़ डेस्क",status:String(f.get("status")),views:"—",date:"अभी"},...articles]);notify("नई खबर सेव हुई");setTab("समाचार")}else notify(`${type} सेव हुआ`)}
 if(tab==="टीम और भूमिकाएँ")return <TeamManager notify={notify} currentEmail={currentEmail}/>;
 if(tab==="ऑडियो हाइलाइट्स")return <AudioHighlightsManager notify={notify}/>;
 if(tab==="समाचार")return <NewsManager mode="list" setTab={setTab} notify={notify}/>;
 if(tab==="नई पोस्ट")return <NewsManager mode="create" setTab={setTab} notify={notify}/>;
 if(tab==="श्रेणियाँ")return <Manager title="श्रेणियाँ" items={cats} onAdd={x=>{setCats([...cats,x]);notify("श्रेणी जोड़ी गई")}} onEdit={(old,next)=>{setCats(cats.map(x=>x===old?next:x));notify("श्रेणी अपडेट हुई")}}/>;
 if(tab==="रिपोर्टर")return <Manager title="रिपोर्टर" items={reporters} onAdd={x=>{setReporters([...reporters,x]);notify("रिपोर्टर जोड़ा गया")}} onEdit={(old,next)=>{setReporters(reporters.map(x=>x===old?next:x));notify("रिपोर्टर अपडेट हुआ")}}/>;
 if(tab==="मीडिया लाइब्रेरी")return <section className="workspace"><div className="workspaceHead"><div><h2>मीडिया लाइब्रेरी</h2><p>फोटो और वीडियो प्रबंधित करें</p></div><label className="primary uploadBtn">＋ अपलोड<input type="file" hidden onChange={e=>{if(e.target.files?.[0]){setAssets([...assets,e.target.files[0].name]);notify("मीडिया अपलोड हुआ")}}}/></label></div><div className="mediaGrid">{assets.map((x,i)=><article key={x}><div>{i===2?"▶":"▧"}</div><b>{x}</b><small>{i===2?"वीडियो":"फोटो"}</small></article>)}</div></section>;
 if(tab==="ब्रेकिंग न्यूज़")return <BreakingManager notify={notify}/>;
 if(tab==="विज्ञापन")return <section className="workspace"><div className="workspaceHead"><div><h2>विज्ञापन अभियान</h2><p>वेबसाइट विज्ञापन बनाएँ और सक्रिय करें</p></div></div><form className="editorForm" onSubmit={e=>submit(e,"विज्ञापन")}><label>अभियान नाम<input required placeholder="अभियान का नाम"/></label><div><label>प्लेसमेंट<select><option>होमपेज टॉप</option><option>साइडबार</option><option>खबर के बीच</option></select></label><label>लिंक<input type="url" placeholder="https://"/></label></div><label>बैनर<input type="file" accept="image/*"/></label><button className="primary">अभियान सेव करें</button></form></section>;
 if(tab==="टिप्पणियाँ")return <section className="workspace"><div className="workspaceHead"><div><h2>टिप्पणी मॉडरेशन</h2><p>12 टिप्पणियाँ समीक्षा में हैं</p></div></div><div className="commentList">{["बहुत उपयोगी जानकारी","कृपया इस खबर का स्रोत बताएं","हमारे शहर की खबर भी प्रकाशित करें"].map(x=><article key={x}><div><b>पाठक</b><p>{x}</p></div><button onClick={()=>notify("टिप्पणी स्वीकृत हुई")}>स्वीकार</button><button onClick={()=>notify("टिप्पणी हटाई गई")}>हटाएँ</button></article>)}</div></section>;
 return <section className="workspace"><div className="workspaceHead"><div><h2>वेबसाइट सेटिंग्स</h2><p>न्यूज़रूम की सामान्य जानकारी</p></div></div><form className="editorForm" onSubmit={e=>submit(e,"सेटिंग्स")}><label>वेबसाइट नाम<input defaultValue="NEWS24x7 INDIA"/></label><label>टैगलाइन<input defaultValue="सच दिखाने की हिम्मत"/></label><label>संपर्क ईमेल<input type="email" defaultValue="news@news24x7india.com"/></label><button className="primary">सेटिंग्स सेव करें</button></form></section>}

function Manager({title,items,onAdd,onEdit}:{title:string;items:string[];onAdd:(x:string)=>void;onEdit:(old:string,next:string)=>void}){const[value,setValue]=useState("");return <section className="workspace"><div className="workspaceHead"><div><h2>{title}</h2><p>{items.length} रिकॉर्ड उपलब्ध हैं</p></div></div><form className="inlineAdd" onSubmit={e=>{e.preventDefault();if(value.trim()){onAdd(value);setValue("")}}}><input value={value} onChange={e=>setValue(e.target.value)} placeholder={`नई ${title} का नाम`}/><button className="primary">＋ जोड़ें</button></form><div className="managerList">{items.map((x,i)=><article key={x}><b>{x}</b><span>{i%2?"सक्रिय":"प्रकाशित"}</span><button onClick={()=>{const next=window.prompt("नया नाम",x);if(next?.trim())onEdit(x,next.trim())}}>संपादित करें</button></article>)}</div></section>}
