"use client";
import {FormEvent,useState,useSyncExternalStore} from "react";
import Link from "next/link";
import BreakingManager from "./BreakingManager";
import TeamManager from "./TeamManager";
import AudioHighlightsManager from "./AudioHighlightsManager";
import NewsManager from "./NewsManager";
import CategoryManager from "./CategoryManager";
type Props={user:{name:string,email:string};roleLabel:string;allowed:string[];signout:string};
type AdminLanguage="hi"|"en";
const ADMIN_LANGUAGE_KEY="news24x7-admin-language";
const nav=["डैशबोर्ड","समाचार","नई पोस्ट","श्रेणियाँ","रिपोर्टर","ब्रेकिंग न्यूज़","ऑडियो हाइलाइट्स","विज्ञापन","मीडिया लाइब्रेरी","टिप्पणियाँ","टीम और भूमिकाएँ"];
const englishLabels:Record<string,string>={"डैशबोर्ड":"Dashboard","समाचार":"News","नई पोस्ट":"New post","श्रेणियाँ":"Categories","रिपोर्टर":"Reporters","ब्रेकिंग न्यूज़":"Breaking news","ऑडियो हाइलाइट्स":"Audio highlights","विज्ञापन":"Advertising","मीडिया लाइब्रेरी":"Media library","टिप्पणियाँ":"Comments","टीम और भूमिकाएँ":"Team and roles","सेटिंग्स":"Settings","सुपर एडमिन":"Super admin","एडमिन":"Admin","मुख्य संपादक":"Editor in chief","विज्ञापन प्रबंधक":"Ad manager"};
function localize(language:AdminLanguage,hindi:string,english?:string){return language==="en"?(english??englishLabels[hindi]??hindi):hindi}
function subscribeLanguage(callback:()=>void){window.addEventListener("storage",callback);window.addEventListener("admin-language-change",callback);return()=>{window.removeEventListener("storage",callback);window.removeEventListener("admin-language-change",callback)}}
function getLanguageSnapshot():AdminLanguage{return window.localStorage.getItem(ADMIN_LANGUAGE_KEY)==="en"?"en":"hi"}
const baseArticles=[
 {title:"प्रदेश के छोटे शहरों में युवाओं के लिए खुल रहे रोजगार के द्वार",category:"मध्य प्रदेश",author:"राहुल राठौर",status:"प्रकाशित",views:"18.4K",date:"24 अगस्त, 10:32"},
 {title:"राष्ट्रीय प्रतियोगिता में युवा खिलाड़ियों ने रचा इतिहास",category:"खेल",author:"संदीप शर्मा",status:"प्रकाशित",views:"12.1K",date:"24 अगस्त, 09:18"},
 {title:"डिजिटल कक्षाओं से गांव के विद्यार्थियों को मिली नई दिशा",category:"शिक्षा",author:"न्यूज़ डेस्क",status:"ड्राफ्ट",views:"—",date:"23 अगस्त, 18:42"},
];
export default function AdminDashboard({user,roleLabel,allowed,signout}:Props){const[tab,setTab]=useState("डैशबोर्ड");const[articles,setArticles]=useState(baseArticles);const[breaking,setBreaking]=useState("राष्ट्रीय राजमार्ग परियोजना को मिली मंजूरी");const[toast,setToast]=useState("");const[menu,setMenu]=useState(false);const language=useSyncExternalStore(subscribeLanguage,getLanguageSnapshot,()=>"hi");function setLanguage(next:AdminLanguage){window.localStorage.setItem(ADMIN_LANGUAGE_KEY,next);document.documentElement.lang=next;window.dispatchEvent(new Event("admin-language-change"))}function notify(x:string){setToast(x);setTimeout(()=>setToast(""),2200)}return <div className="adminShell" lang={language}>
 <aside className={`adminNav ${menu?"open":""}`}><Link className="adminBrand" href="/"><b>NEWS<span>24x7</span></b><small>ADMIN DESK</small></Link><nav>{nav.filter(x=>allowed.includes(x)).map((x,i)=><button key={x} className={tab===x?"active":""} onClick={()=>{setTab(x);setMenu(false)}}><i>{["▦","▤","＋","◫","♙","⚡","▣","▧","◌","♜"][i]}</i>{localize(language,x)}{x==="टिप्पणियाँ"&&<em>12</em>}</button>)}</nav><div className="navBottom">{allowed.includes("सेटिंग्स")&&<button onClick={()=>setTab("सेटिंग्स")}>⚙ {localize(language,"सेटिंग्स")}</button>}<a href={signout}>↪ {localize(language,"साइन आउट","Sign out")}</a></div></aside>
 <main className="adminMain"><header><div><button className="mobileMenu" onClick={()=>setMenu(!menu)}>☰</button><h1>{localize(language,tab)}</h1><p>{localize(language,`नमस्कार, ${user.name.split(" ")[0]} — न्यूज़रूम में आपका स्वागत है।`,`Hello, ${user.name.split(" ")[0]} — welcome to the newsroom.`)}</p></div><div className="adminActions"><button className="languageToggle" type="button" title={localize(language,"English में बदलें","हिन्दी में बदलें")} aria-label={localize(language,"डैशबोर्ड भाषा English करें","Switch dashboard language to Hindi")} onClick={()=>{const next=language==="hi"?"en":"hi";setLanguage(next);notify(next==="en"?"Dashboard language changed to English":"डैशबोर्ड भाषा हिन्दी की गई")}}><span aria-hidden="true">🌐</span>{language==="hi"?"EN":"हिन्दी"}</button><button className="bell" aria-label={localize(language,"सूचनाएँ","Notifications")} onClick={()=>notify(localize(language,"कोई नई सूचना नहीं","No new notifications"))}>♢<i/></button><div className="avatar">{user.name.slice(0,1).toUpperCase()}</div><div><b>{user.name}</b><small>{localize(language,roleLabel)}</small></div></div></header>
 {tab==="डैशबोर्ड"?<Dashboard language={language} articles={articles} breaking={breaking} setBreaking={setBreaking} setTab={setTab}/>:<Workspace language={language} setLanguage={setLanguage} tab={tab} setTab={setTab} articles={articles} setArticles={setArticles} notify={notify} currentEmail={user.email}/>}
 </main>{toast&&<div className="adminToast">✓ {toast}</div>}</div>}

function Dashboard({language,articles,breaking,setBreaking,setTab}:{language:AdminLanguage;articles:typeof baseArticles;breaking:string;setBreaking:(x:string)=>void;setTab:(x:string)=>void}){const stats=language==="en"?[["Today's views","48,294","↑ 12.4%","◉"],["Published stories","2,048","+8 today","▤"],["Total reporters","32","28 active","♙"],["Advertising revenue","₹84,500","This month","▣"]]:[["आज के व्यूज़","48,294","↑ 12.4%","◉"],["प्रकाशित खबरें","2,048","+8 आज","▤"],["कुल रिपोर्टर","32","28 सक्रिय","♙"],["विज्ञापन आय","₹84,500","इस माह","▣"]];const quick=language==="en"?[["＋","नई पोस्ट","Create and publish an article"],["▧","मीडिया लाइब्रेरी","Add photos and videos"],["♙","रिपोर्टर","Create a team member profile"],["▣","विज्ञापन","Create an advertising campaign"]]:[["＋","नई पोस्ट","लेख बनाएं और प्रकाशित करें"],["▧","मीडिया लाइब्रेरी","फोटो और वीडियो जोड़ें"],["♙","रिपोर्टर","नई टीम सदस्य प्रोफाइल"],["▣","विज्ञापन","नया विज्ञापन अभियान"]];return <><section className="statsGrid">{stats.map(s=><article key={s[0]}><div className="statIcon">{s[3]}</div><span>{s[0]}</span><strong>{s[1]}</strong><small>{s[2]}</small></article>)}</section><section className="breakingEditor"><div><span>⚡ {localize(language,"लाइव ब्रेकिंग न्यूज़","Live breaking news")}</span><p>{localize(language,"कई हेडलाइन जोड़ें और नियंत्रित करें","Add and manage multiple headlines")}</p></div><input value={breaking} onChange={e=>setBreaking(e.target.value)} readOnly/><button onClick={()=>setTab("ब्रेकिंग न्यूज़")}>{localize(language,"सभी मैनेज करें","Manage all")}</button><label><input type="checkbox" defaultChecked disabled/> {localize(language,"लाइव","Live")}</label></section><section className="adminGrid"><ArticleTable language={language} articles={articles} setTab={setTab}/><aside className="adminSide"><div className="panel quick"><h2>{localize(language,"त्वरित कार्य","Quick actions")}</h2>{quick.map(x=><button key={x[1]} onClick={()=>setTab(x[1])}><i>{x[0]}</i><span><b>{localize(language,x[1])}</b><small>{x[2]}</small></span><em>›</em></button>)}</div><div className="panel activity"><h2>{localize(language,"हाल की गतिविधि","Recent activity")}</h2>{(language==="en"?["Rahul published a story","Sandeep updated a draft","Advertising campaign activated"]:["राहुल ने खबर प्रकाशित की","संदीप ने ड्राफ्ट अपडेट किया","विज्ञापन अभियान सक्रिय हुआ"]).map((x,i)=><div key={x}><i>{language==="en"?["R","S","A"][i]:["र","स","वि"][i]}</i><p><b>{x}</b><small>{i+1} {localize(language,"घंटे पहले","hours ago")}</small></p></div>)}</div></aside></section></>}
function ArticleTable({language,articles,setTab}:{language:AdminLanguage;articles:typeof baseArticles;setTab:(x:string)=>void}){return <div className="panel"><div className="panelHead"><div><h2>{localize(language,"हाल की खबरें","Recent stories")}</h2><p>{localize(language,"समाचारों को संपादित और प्रकाशित करें","Edit and publish news stories")}</p></div><button className="primary" onClick={()=>setTab("नई पोस्ट")}>＋ {localize(language,"नई खबर लिखें","Write new story")}</button></div><div className="tableWrap"><table><thead><tr><th>{localize(language,"शीर्षक","Title")}</th><th>{localize(language,"श्रेणी","Category")}</th><th>{localize(language,"लेखक","Author")}</th><th>{localize(language,"स्थिति","Status")}</th><th>{localize(language,"व्यूज़","Views")}</th><th>{localize(language,"अपडेट","Updated")}</th></tr></thead><tbody>{articles.map(a=><tr key={a.title}><td><b>{a.title}</b></td><td><span className="pill">{a.category}</span></td><td>{a.author}</td><td><span className={`status ${a.status}`}>● {a.status}</span></td><td>{a.views}</td><td>{a.date}</td></tr>)}</tbody></table></div><button className="viewAll" onClick={()=>setTab("समाचार")}>{localize(language,"सभी समाचार देखें","View all news")} →</button></div>}

function Workspace({language,setLanguage,tab,setTab,articles,setArticles,notify,currentEmail}:{language:AdminLanguage;setLanguage:(language:AdminLanguage)=>void;tab:string;setTab:(x:string)=>void;articles:typeof baseArticles;setArticles:(x:typeof baseArticles)=>void;notify:(x:string)=>void;currentEmail:string}){const[reporters,setReporters]=useState(["राहुल राठौर","संदीप शर्मा","प्रिया शर्मा"]);const[assets,setAssets]=useState(["राज्य-विकास.jpg","खेल-महोत्सव.jpg","शिक्षा-अभियान.mp4"]);function submit(e:FormEvent<HTMLFormElement>,type:string){e.preventDefault();const f=new FormData(e.currentTarget);if(type==="article"){const title=String(f.get("title"));setArticles([{title,category:String(f.get("category")),author:"न्यूज़ डेस्क",status:String(f.get("status")),views:"—",date:"अभी"},...articles]);notify("नई खबर सेव हुई");setTab("समाचार")}else notify(localize(language,`${type} सेव हुआ`,`${englishLabels[type]??type} saved`))}
 if(tab==="टीम और भूमिकाएँ")return <TeamManager notify={notify} currentEmail={currentEmail}/>;
 if(tab==="ऑडियो हाइलाइट्स")return <AudioHighlightsManager notify={notify}/>;
 if(tab==="समाचार")return <NewsManager mode="list" setTab={setTab} notify={notify}/>;
 if(tab==="नई पोस्ट")return <NewsManager mode="create" setTab={setTab} notify={notify}/>;
 if(tab==="श्रेणियाँ")return <CategoryManager language={language} notify={notify}/>;
 if(tab==="रिपोर्टर")return <Manager title="रिपोर्टर" items={reporters} onAdd={x=>{setReporters([...reporters,x]);notify("रिपोर्टर जोड़ा गया")}} onEdit={(old,next)=>{setReporters(reporters.map(x=>x===old?next:x));notify("रिपोर्टर अपडेट हुआ")}}/>;
 if(tab==="मीडिया लाइब्रेरी")return <section className="workspace"><div className="workspaceHead"><div><h2>मीडिया लाइब्रेरी</h2><p>फोटो और वीडियो प्रबंधित करें</p></div><label className="primary uploadBtn">＋ अपलोड<input type="file" hidden onChange={e=>{if(e.target.files?.[0]){setAssets([...assets,e.target.files[0].name]);notify("मीडिया अपलोड हुआ")}}}/></label></div><div className="mediaGrid">{assets.map((x,i)=><article key={x}><div>{i===2?"▶":"▧"}</div><b>{x}</b><small>{i===2?"वीडियो":"फोटो"}</small></article>)}</div></section>;
 if(tab==="ब्रेकिंग न्यूज़")return <BreakingManager notify={notify}/>;
 if(tab==="विज्ञापन")return <section className="workspace"><div className="workspaceHead"><div><h2>विज्ञापन अभियान</h2><p>वेबसाइट विज्ञापन बनाएँ और सक्रिय करें</p></div></div><form className="editorForm" onSubmit={e=>submit(e,"विज्ञापन")}><label>अभियान नाम<input required placeholder="अभियान का नाम"/></label><div><label>प्लेसमेंट<select><option>होमपेज टॉप</option><option>साइडबार</option><option>खबर के बीच</option></select></label><label>लिंक<input type="url" placeholder="https://"/></label></div><label>बैनर<input type="file" accept="image/*"/></label><button className="primary">अभियान सेव करें</button></form></section>;
 if(tab==="टिप्पणियाँ")return <section className="workspace"><div className="workspaceHead"><div><h2>टिप्पणी मॉडरेशन</h2><p>12 टिप्पणियाँ समीक्षा में हैं</p></div></div><div className="commentList">{["बहुत उपयोगी जानकारी","कृपया इस खबर का स्रोत बताएं","हमारे शहर की खबर भी प्रकाशित करें"].map(x=><article key={x}><div><b>पाठक</b><p>{x}</p></div><button onClick={()=>notify("टिप्पणी स्वीकृत हुई")}>स्वीकार</button><button onClick={()=>notify("टिप्पणी हटाई गई")}>हटाएँ</button></article>)}</div></section>;
 return <section className="workspace"><div className="workspaceHead"><div><h2>{localize(language,"वेबसाइट सेटिंग्स","Website settings")}</h2><p>{localize(language,"न्यूज़रूम की सामान्य जानकारी","General newsroom preferences")}</p></div></div><form className="editorForm settingsForm" onSubmit={e=>submit(e,"सेटिंग्स")}><label>{localize(language,"डैशबोर्ड भाषा","Dashboard language")}<select value={language} onChange={event=>setLanguage(event.target.value as AdminLanguage)}><option value="hi">हिन्दी</option><option value="en">English</option></select><small className="settingHint">{localize(language,"यह भाषा इसी ब्राउज़र में सेव रहेगी।","This language will remain saved in this browser.")}</small></label><label>{localize(language,"वेबसाइट नाम","Website name")}<input defaultValue="NEWS24x7 INDIA"/></label><label>{localize(language,"टैगलाइन","Tagline")}<input defaultValue="सच दिखाने की हिम्मत"/></label><label>{localize(language,"संपर्क ईमेल","Contact email")}<input type="email" defaultValue="news@news24x7india.com"/></label><button className="primary">{localize(language,"सेटिंग्स सेव करें","Save settings")}</button></form></section>}

function Manager({title,items,onAdd,onEdit}:{title:string;items:string[];onAdd:(x:string)=>void;onEdit:(old:string,next:string)=>void}){const[value,setValue]=useState("");return <section className="workspace"><div className="workspaceHead"><div><h2>{title}</h2><p>{items.length} रिकॉर्ड उपलब्ध हैं</p></div></div><form className="inlineAdd" onSubmit={e=>{e.preventDefault();if(value.trim()){onAdd(value);setValue("")}}}><input value={value} onChange={e=>setValue(e.target.value)} placeholder={`नई ${title} का नाम`}/><button className="primary">＋ जोड़ें</button></form><div className="managerList">{items.map((x,i)=><article key={x}><b>{x}</b><span>{i%2?"सक्रिय":"प्रकाशित"}</span><button onClick={()=>{const next=window.prompt("नया नाम",x);if(next?.trim())onEdit(x,next.trim())}}>संपादित करें</button></article>)}</div></section>}
