'use client';
import {useEffect,useState} from 'react';
const choices=[['light','Light / लाइट'],['black','Pure black + white + red'],['charcoal','Charcoal + white + red'],['warm','Warm dark gray + cream + red']];
export default function AppearanceSettings(){
 const [theme,setTheme]=useState('black'),[allowed,setAllowed]=useState(false),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{let active=true;Promise.all([fetch('/api/backend/auth/me').then(r=>r.json()),fetch('/api/backend/appearance').then(r=>{if(!r.ok)throw Error();return r.json()})]).then(([auth,data])=>{if(active){setAllowed(['admin','super_admin'].includes(auth.user?.role));setTheme(data.theme||'black');setReady(true)}}).catch(()=>{if(active)setMessage('Unable to load theme settings. Reload to retry.')});return()=>{active=false}},[]);
 async function save(){setBusy(true);setMessage('');try{const r=await fetch('/api/backend/appearance',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({theme})});if(!r.ok)throw Error();setMessage('Default theme saved. Visitors keep their own light/dark preference.');window.dispatchEvent(new Event('site-appearance-changed'))}catch{setMessage('Theme was not saved. Check permissions and retry.')}finally{setBusy(false)}}
 return <section className="editorForm"><h2>Website theme / वेबसाइट थीम</h2><p>Choose the default appearance. Visitors can still switch light/dark; dark mode uses the selected palette. Choosing Light keeps the last saved dark palette. Only admins and super admins can save.</p><label>Color palette<select value={theme} disabled={!ready||!allowed||busy} onChange={e=>setTheme(e.target.value)}>{choices.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><button type="button" className="primary" disabled={!ready||!allowed||busy} onClick={save}>{busy?'Saving…':'Apply to website'}</button>{ready&&!allowed&&<p>Only admins and super admins can change this setting.</p>}<p role="status">{message}</p></section>;
}
