"use client";
import {useEffect,useRef,useState,type FormEvent} from 'react';
import './media-library.css';
type Item={id:string;filename:string;title:string;altText:string;caption:string;type:'image'|'video'|'audio';mime:string;size:number;year:string;month:string;modifiedAt:string;usageCount:number;deletedAt:string|null;url:string;publicUrl:string|null;canManage:boolean};
type Listing={items:Item[];total:number;page:number;pages:number;years:string[];indexing:boolean;indexed:number;indexError:string;canSync:boolean};
const endpoint='/api/backend/media';
async function api(url:string,options?:RequestInit){const response=await fetch(url,{cache:'no-store',...options});const text=await response.text();let data;try{data=JSON.parse(text)}catch{throw new Error(response.status===413?'File is too large.':'Unable to load media. Please retry.')}if(!response.ok)throw new Error(data.detail||'Media request failed');return data}
const bytes=(n:number)=>n>=1024*1024?(n/1024/1024).toFixed(1)+' MB':Math.ceil(n/1024)+' KB';
function Preview({item}:{item:Item}){if(item.deletedAt)return <div className="libraryTrashed">Trash · {item.type}</div>;return item.type==='image'?<img src={item.url} alt={item.altText||item.title||item.filename} loading="lazy"/>:item.type==='video'?<video src={item.url} controls preload="none" aria-label={item.title||item.filename}/>:<div className="libraryAudio"><span aria-hidden="true">♫</span><audio src={item.url} controls preload="none" aria-label={item.title||item.filename}/></div>}
export default function MediaLibraryManager({language,notify}:{language:'hi'|'en';notify:(message:string)=>void}){
 const t=(hi:string,en:string)=>language==='hi'?hi:en;
 const [listing,setListing]=useState<Listing|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[revision,setRevision]=useState(0);
 const [search,setSearch]=useState(''),[query,setQuery]=useState(''),[type,setType]=useState(''),[year,setYear]=useState(''),[month,setMonth]=useState(''),[trash,setTrash]=useState(false),[page,setPage]=useState(1),[selected,setSelected]=useState<Item|null>(null);
 const uploadInput=useRef<HTMLInputElement>(null),editor=useRef<HTMLDivElement>(null);
 useEffect(()=>{const controller=new AbortController();let timer:ReturnType<typeof setTimeout>|undefined;setLoading(true);api(endpoint+'?'+new URLSearchParams({q:query,type,year,month,trash:trash?'1':'0',page:String(page)}),{signal:controller.signal}).then((data:Listing)=>{if(controller.signal.aborted)return;setListing(data);setError('');if(data.indexing)timer=setTimeout(()=>setRevision(r=>r+1),4000)}).catch(e=>{if(!controller.signal.aborted)setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>{controller.abort();clearTimeout(timer)}},[query,type,year,month,trash,page,revision]);
 useEffect(()=>{if(selected){editor.current?.focus({preventScroll:true});editor.current?.scrollIntoView({behavior:'smooth',block:'start'})}},[selected?.id]);
 function filter(change:()=>void){change();setPage(1);setSelected(null)}
 async function action(work:()=>Promise<unknown>,message:string){setBusy(true);setError('');try{await work();setSelected(null);setRevision(r=>r+1);notify(message)}catch(e){setError(e instanceof Error?e.message:'Request failed')}finally{setBusy(false)}}
 function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;const id=selected.id;const data=new FormData(e.currentTarget);const file=data.get('file');if(file instanceof File&&!file.size)data.delete('file');void action(()=>api(endpoint+'/'+id,{method:'PATCH',body:data}),t('मीडिया अपडेट हुआ','Media updated'))}
 return <section className="workspace mediaLibraryManager"><div className="workspaceHead"><div><h2>{t('मीडिया लाइब्रेरी','Media library')}</h2><p>{t('सभी स्थानीय फोटो, वीडियो और ऑडियो — एक जगह','All local images, videos and audio in one place')}</p></div><button className="primary" disabled={busy} onClick={()=>uploadInput.current?.click()}>{t('+ अपलोड','+ Upload')}</button><input ref={uploadInput} type="file" hidden accept="image/jpeg,image/png,image/webp,image/gif,image/avif,video/mp4,video/webm,audio/mpeg" onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file){const data=new FormData();data.set('file',file);void action(()=>api(endpoint,{method:'POST',body:data}),t('मीडिया अपलोड हुआ','Media uploaded'))}}}/></div>
 <p className="libraryHelp">{t('फोटो: 8 MB · वीडियो: 40 MB · MP3: 25 MB। इस्तेमाल हो रही फाइलें हटाई नहीं जा सकतीं।','Images: 8 MB · Videos: 40 MB · MP3: 25 MB. Files currently used in posts cannot be deleted.')}</p>
 <form className="libraryFilters" onSubmit={e=>{e.preventDefault();filter(()=>setQuery(search))}}><label>{t('खोजें','Search')}<input value={search} onChange={e=>setSearch(e.target.value)} placeholder={t('फाइल का नाम या शीर्षक','Filename or title')}/></label><button type="submit">{t('खोजें','Search')}</button><label>{t('प्रकार','Type')}<select value={type} onChange={e=>filter(()=>setType(e.target.value))}><option value="">{t('सभी प्रकार','All types')}</option><option value="image">{t('फोटो','Images')}</option><option value="video">{t('वीडियो','Videos')}</option><option value="audio">{t('ऑडियो','Audio')}</option></select></label><label>{t('वर्ष','Year')}<select value={year} onChange={e=>filter(()=>setYear(e.target.value))}><option value="">{t('सभी वर्ष','All years')}</option>{listing?.years.map(y=><option key={y}>{y}</option>)}</select></label><label>{t('महीना','Month')}<select value={month} onChange={e=>filter(()=>setMonth(e.target.value))}><option value="">{t('सभी महीने','All months')}</option>{Array.from({length:12},(_,i)=>String(i+1).padStart(2,'0')).map(m=><option key={m}>{m}</option>)}</select></label><label>{t('स्थिति','Status')}<select value={trash?'trash':'active'} onChange={e=>filter(()=>setTrash(e.target.value==='trash'))}><option value="active">{t('लाइब्रेरी','Library')}</option><option value="trash">{t('हटाई गई फाइलें','Trash')}</option></select></label><button type="button" disabled={busy||listing?.indexing} onClick={()=>void action(()=>listing?.canSync?api(endpoint+'/sync',{method:'POST'}):Promise.resolve(),t('लाइब्रेरी रिफ्रेश हुई','Library refreshed'))}>{t('रिफ्रेश','Refresh')}</button></form>
 {error&&<p className="libraryError" role="alert">{error}</p>}
 <p className="libraryStatus" role="status">{listing?listing.total.toLocaleString(language==='hi'?'hi-IN':'en-IN')+' '+t('फाइलें','files'):t('लोड हो रहा है…','Loading…')}{listing?.indexing?' · '+t('अपलोड फ़ोल्डर स्कैन हो रहा है…','Scanning uploads folder…'):''}{loading&&listing?' · '+t('लोड हो रहा है…','Loading…'):''}</p>{listing?.indexError&&<p role="alert">{listing.indexError}</p>}
 {selected&&<div className="libraryEditor" ref={editor} tabIndex={-1}><div className="libraryEditorHead"><h3>{t('मीडिया संपादित करें','Edit media')}</h3><button onClick={()=>setSelected(null)} disabled={busy}>{t('बंद करें','Close')}</button></div><div className="libraryEditorLayout"><div><Preview item={selected}/><p className="libraryFilename">{selected.filename}</p><p>{selected.type} · {bytes(selected.size)} · {selected.year}/{selected.month}</p><a href={selected.url} target="_blank" rel="noreferrer">{t('फाइल खोलें','Open file')}</a>{selected.publicUrl&&<button type="button" onClick={()=>{void navigator.clipboard.writeText(new URL(selected.publicUrl!,location.origin).href).then(()=>notify(t('लिंक कॉपी हुआ','Link copied'))).catch(()=>setError('Could not copy link'))}}>{t('लिंक कॉपी करें','Copy URL')}</button>}</div><form key={selected.id} onSubmit={save}><label>{t('शीर्षक / नाम','Title / display name')}<input name="title" maxLength={300} defaultValue={selected.title} disabled={!selected.canManage}/></label><label>{t('वैकल्पिक पाठ','Alternative text')}<input name="altText" maxLength={500} defaultValue={selected.altText} disabled={!selected.canManage}/></label><label>{t('कैप्शन','Caption')}<textarea name="caption" maxLength={2000} defaultValue={selected.caption} disabled={!selected.canManage}/></label>{selected.canManage&&<><label>{t('फाइल बदलें (उसी फ़ॉर्मेट में)','Replace file (same format)')}<input type="file" name="file" accept={selected.mime}/></label><small>{t('पुराना URL सुरक्षित रहेगा। फाइल का असली नाम बदलना आवश्यक नहीं है।','Existing URLs are preserved. Physical filenames are not renamed.')}</small><button className="primary" disabled={busy}>{busy?t('सेव हो रहा है…','Saving…'):t('सेव करें','Save changes')}</button></>}</form></div></div>}
 <div className="libraryGrid" aria-busy={loading}>{listing?.items.map(item=><article className="libraryCard" key={item.id}><div className="libraryPreview"><Preview item={item}/></div><div className="libraryCardInfo"><h3 title={item.filename}>{item.title||item.filename}</h3><p>{item.type} · {bytes(item.size)} · {item.year}/{item.month}</p><p>{item.usageCount?t(`${item.usageCount} पोस्ट में उपयोग`, `Used in ${item.usageCount} record(s)`):t('कोई पोस्ट लिंक नहीं','No linked posts')}</p><div className="libraryCardActions">{!item.deletedAt&&<button disabled={busy} onClick={()=>{setSelected(item);editor.current?.scrollIntoView({behavior:'smooth',block:'start'})}}>{item.canManage?t('संपादित करें','Edit'):t('देखें','View')}</button>}{item.canManage&&(item.deletedAt?<><button disabled={busy} onClick={()=>void action(()=>api(endpoint+'/'+item.id+'/restore',{method:'POST'}),t('फाइल वापस आई','File restored'))}>{t('वापस लाएं','Restore')}</button><button className="libraryDelete" disabled={busy} onClick={()=>{if(confirm(t('क्या आप वाकई इस फाइल को पूरी तरह से हटाना चाहते हैं? यह वापस नहीं आ सकेगी।','Are you sure you want to permanently delete this file? This cannot be undone.')))void action(()=>api(endpoint+'/'+item.id+'/permanent',{method:'DELETE'}),t('फाइल पूरी तरह से हटाई गई','File permanently deleted'))}}>{t('पूरी तरह से हटाएं','Delete Permanently')}</button></>:<button className="libraryDelete" disabled={busy||item.usageCount>0} title={item.usageCount?'Remove post references first':undefined} onClick={()=>{if(confirm(t('इस फाइल को हटाई गई फाइलों में भेजें? बाद में वापस ला सकते हैं।','Move this file to trash? You can restore it later.')))void action(()=>api(endpoint+'/'+item.id,{method:'DELETE'}),t('फाइल हटाई गई; वापस ला सकते हैं','File moved to recoverable trash'))}}>{t('हटाएं','Delete')}</button>)}</div></div></article>)}</div>
 {!loading&&listing&&!listing.items.length&&<p className="libraryEmpty">{listing.indexing?t('फाइलें स्कैन हो रही हैं…','Files are being indexed…'):t('कोई फाइल नहीं मिली। फ़िल्टर बदलें या नई फाइल अपलोड करें।','No files found. Change filters or upload a file.')}</p>}
 {listing&&<div className="libraryPagination"><button disabled={loading||busy||listing.page<=1} onClick={()=>{setPage(listing.page-1);setSelected(null)}}>{t('← पिछला','← Previous')}</button><span>{listing.page} / {listing.pages}</span><button disabled={loading||busy||listing.page>=listing.pages} onClick={()=>{setPage(listing.page+1);setSelected(null)}}>{t('अगला →','Next →')}</button></div>}
 </section>
}
