import {Readable} from "node:stream";
import {Router} from "express";
import multer from "multer";
import {ObjectId,type Document,type WithId} from "mongodb";
import {articleImages,db} from "../database.js";
import {articleResponse} from "../serializers.js";
import {getCurrentUser,requirePermission,rolePermissions} from "../security.js";
import type {AuthedRequest} from "../types.js";
import {AppError,asyncRoute,escapeRegex,objectId,routeParam,slugifyTitle} from "../utils.js";
import {articleSchema} from "../validation.js";

export const articlesRouter=Router();
const imageTypes=new Set(["image/jpeg","image/png","image/webp"]);
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:8*1024*1024},fileFilter:(_request,file,callback)=>imageTypes.has(file.mimetype)?callback(null,true):callback(new AppError(415,"Only JPG, PNG and WebP news images are allowed"))});
async function uniqueSlug(value:string){const base=slugifyTitle(value);let slug=base,suffix=2;while(await db.collection("articles").findOne({slug})){slug=`${base}-${suffix++}`}return slug}
function parseBody(body:Record<string,unknown>){return articleSchema.parse({...body,featured:body.featured===true||body.featured==="true"||body.featured==="on"})}
async function saveImage(file:Express.Multer.File){const stream=articleImages.openUploadStream(file.originalname,{contentType:file.mimetype});await new Promise<void>((resolve,reject)=>Readable.from(file.buffer).pipe(stream).once("error",reject).once("finish",()=>resolve()));return stream.id}
articlesRouter.get("/",asyncRoute(async(request:AuthedRequest,response)=>{
  const page=Math.max(1,Number(request.query.page)||1),limit=Math.max(1,Math.min(50,Number(request.query.limit)||12));const query:Record<string,unknown>={};
  if(request.query.admin==="true"){const user=await getCurrentUser(request);const allowed=rolePermissions[user.role]??new Set();if(!allowed.has("*")&&!allowed.has("articles"))throw new AppError(403,"Insufficient permission");if(request.query.status)query.status=String(request.query.status)}else query.status="published";
  if(request.query.category)query.category=String(request.query.category);
  const search=String(request.query.q||"").trim();if(search){const escaped=escapeRegex(search),slugTerm=escapeRegex(search.replace(/[\s_]+/g,"-"));query.$or=["title","excerpt","category","author_name","seo_keywords"].map(field=>({[field]:{$regex:escaped,$options:"i"}})).concat([{slug:{$regex:slugTerm,$options:"i"}}])}
  const collection=db.collection("articles");const [total,items,categories]=await Promise.all([collection.countDocuments(query),collection.find(query).sort({published_at:-1}).skip((page-1)*limit).limit(limit).toArray(),collection.distinct("category",{status:"published"})]);
  response.json({items:items.map(item=>articleResponse(item,request.query.admin==="true")),page,limit,total,pages:Math.max(1,Math.ceil(total/limit)),categories});
}));
articlesRouter.get("/:itemId/image",asyncRoute(async(request:AuthedRequest,response)=>{const row=await db.collection("articles").findOne({_id:objectId(routeParam(request.params.itemId)),image_file_id:{$exists:true}});if(!row?.image_file_id)throw new AppError(404,"Image not found");if(row.status!=="published"){const user=await getCurrentUser(request);const allowed=rolePermissions[user.role]??new Set();if(!allowed.has("*")&&!allowed.has("articles"))throw new AppError(403,"Insufficient permission")}response.set({"Content-Type":row.image_content_type||"image/jpeg","Cache-Control":row.status==="published"?"public, max-age=86400":"private, no-store"});articleImages.openDownloadStream(row.image_file_id).once("error",error=>response.destroy(error)).pipe(response)}));
articlesRouter.get("/:slug",asyncRoute(async(request,response)=>{const row=await db.collection("articles").findOne({slug:routeParam(request.params.slug),status:"published"});if(!row)throw new AppError(404,"News not found");if(request.query.track_view!=="false")await db.collection("articles").updateOne({_id:row._id},{$inc:{views:1}});response.json(articleResponse(row,true))}));
articlesRouter.post("/",requirePermission("articles"),upload.single("image"),asyncRoute(async(request:AuthedRequest,response)=>{const body=parseBody(request.body),now=new Date(),id=new ObjectId(),document:WithId<Document>={_id:id,...body,slug:await uniqueSlug(body.title),author_id:request.user!._id,author_name:request.user!.name,views:0,created_at:now,updated_at:now,published_at:body.status==="published"?now:null};let imageId;if(request.file){imageId=await saveImage(request.file);document.image_file_id=imageId;document.image_content_type=request.file.mimetype}try{await db.collection("articles").insertOne(document);response.json(articleResponse(document,true))}catch(error){if(imageId)await articleImages.delete(imageId).catch(()=>undefined);throw error}}));
articlesRouter.patch("/:itemId",requirePermission("articles"),upload.single("image"),asyncRoute(async(request,response)=>{const id=objectId(routeParam(request.params.itemId)),body=parseBody(request.body),existing=await db.collection("articles").findOne({_id:id});if(!existing)throw new AppError(404,"News not found");const updates:Record<string,unknown>={...body,updated_at:new Date()};if(body.status==="published"&&!existing.published_at)updates.published_at=new Date();let newImageId;if(request.file){newImageId=await saveImage(request.file);updates.image_file_id=newImageId;updates.image_content_type=request.file.mimetype}const replacingWithUrl=!request.file&&Boolean(body.image_url?.trim());try{await db.collection("articles").updateOne({_id:id},replacingWithUrl?{$set:updates,$unset:{image_file_id:"",image_content_type:""}}:{$set:updates});if((newImageId||replacingWithUrl)&&existing.image_file_id)await articleImages.delete(existing.image_file_id).catch(()=>undefined);response.json({ok:true})}catch(error){if(newImageId)await articleImages.delete(newImageId).catch(()=>undefined);throw error}}));
articlesRouter.delete("/:itemId",requirePermission("articles"),asyncRoute(async(request,response)=>{const row=await db.collection("articles").findOneAndDelete({_id:objectId(routeParam(request.params.itemId))});if(row?.image_file_id)await articleImages.delete(row.image_file_id).catch(()=>undefined);response.json({ok:true})}));
