import {Readable} from "node:stream";
import {Router} from "express";
import multer from "multer";
import {db,audioFiles} from "../database.js";
import {audioResponse} from "../serializers.js";
import {requirePermission} from "../security.js";
import {AppError,asyncRoute,objectId,routeParam} from "../utils.js";

export const audioRouter=Router();
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:25*1024*1024},fileFilter:(_request,file,callback)=>callback(null,file.originalname.toLowerCase().endsWith(".mp3"))});
audioRouter.get("/",asyncRoute(async(request,response)=>{const admin=request.query.admin==="true";if(admin)await new Promise<void>((resolve,reject)=>requirePermission("audio")(request,response,error=>error?reject(error):resolve()));const cursor=db.collection("audio_tracks").find(admin?{}:{active:true}).sort({position:1});if(!admin)cursor.limit(10);const items=await cursor.toArray();response.json({items:items.map(audioResponse)})}));
audioRouter.post("/",requirePermission("audio"),upload.single("audio"),asyncRoute(async(request,response)=>{if(!request.file)throw new AppError(415,"Only MP3 files are allowed");const title=String(request.body.title||"").trim();if(!title)throw new AppError(422,"Title is required");const uploadStream=audioFiles.openUploadStream(request.file.originalname,{contentType:"audio/mpeg"});await new Promise<void>((resolve,reject)=>{Readable.from(request.file!.buffer).pipe(uploadStream).once("error",reject).once("finish",()=>resolve())});const last=await db.collection("audio_tracks").findOne({},{sort:{position:-1}});const document={title,filename:request.file.originalname,size:request.file.size,file_id:uploadStream.id,active:true,position:(last?.position??0)+1,created_at:new Date()};const inserted=await db.collection("audio_tracks").insertOne(document);response.json(audioResponse({...document,_id:inserted.insertedId}))}));
audioRouter.patch("/:itemId",requirePermission("audio"),asyncRoute(async(request,response)=>{const id=objectId(routeParam(request.params.itemId)),current=await db.collection("audio_tracks").findOne({_id:id}),direction=request.body?.direction;if(current&&(direction==="up"||direction==="down")){const up=direction==="up",other=await db.collection("audio_tracks").findOne({position:{[up?"$lt":"$gt"]:current.position}},{sort:{position:up?-1:1}});if(other){await db.collection("audio_tracks").bulkWrite([{updateOne:{filter:{_id:current._id},update:{$set:{position:other.position}}}},{updateOne:{filter:{_id:other._id},update:{$set:{position:current.position}}}}])}}const updates=Object.fromEntries(Object.entries(request.body??{}).filter(([key])=>["title","active","position"].includes(key)));if(Object.keys(updates).length)await db.collection("audio_tracks").updateOne({_id:id},{$set:updates});response.json({ok:true})}));
audioRouter.delete("/:itemId",requirePermission("audio"),asyncRoute(async(request,response)=>{const row=await db.collection("audio_tracks").findOneAndDelete({_id:objectId(routeParam(request.params.itemId))});if(row)await audioFiles.delete(row.file_id).catch(()=>undefined);response.json({ok:true})}));
audioRouter.get("/:itemId/stream",asyncRoute(async(request,response)=>{const row=await db.collection("audio_tracks").findOne({_id:objectId(routeParam(request.params.itemId)),active:true});if(!row)throw new AppError(404,"Not found");response.set({"Content-Type":"audio/mpeg","Content-Disposition":`inline; filename="${String(row.filename).replace(/["\r\n]/g,"")}"`,"Cache-Control":"public, max-age=3600"});audioFiles.openDownloadStream(row.file_id).once("error",error=>response.destroy(error)).pipe(response)}));
