import {spawn} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {createRequire} from 'node:module';
const command=process.argv[2]||'dev';
if(!['dev','build','start'].includes(command))throw Error('Unknown frontend command');
const cli=createRequire(import.meta.url).resolve('next/dist/bin/next');
const root=fileURLToPath(new URL('../',import.meta.url));
const child=spawn(process.execPath,[cli,command,...process.argv.slice(3)],{cwd:root,stdio:'inherit',env:process.env});
child.on('error',error=>{console.error(error.message);process.exitCode=1});
child.on('exit',code=>{process.exitCode=code??1});
for(const signal of ['SIGTERM','SIGINT'])process.on(signal,()=>child.kill(signal));
