import { env } from "cloudflare:workers";
import { getChatGPTUser } from "../../chatgpt-auth";
import { can,getOrBootstrapRole } from "../../admin/roles";
async function ready(){await env.DB.prepare(`CREATE TABLE IF NOT EXISTS breaking_news (id INTEGER PRIMARY KEY AUTOINCREMENT, text TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1, created_at INTEGER NOT NULL)`).run();const count=await env.DB.prepare("SELECT COUNT(*) AS count FROM breaking_news").first<{count:number}>();if(!count?.count)await env.DB.batch([env.DB.prepare("INSERT INTO breaking_news (text,active,created_at) VALUES (?,1,?)").bind("राष्ट्रीय राजमार्ग परियोजना को मिली मंजूरी, कई जिलों को होगा लाभ",Date.now()),env.DB.prepare("INSERT INTO breaking_news (text,active,created_at) VALUES (?,1,?)").bind("प्रदेश में नई रोजगार योजना की घोषणा, युवाओं को मिलेगा प्रशिक्षण",Date.now()+1),env.DB.prepare("INSERT INTO breaking_news (text,active,created_at) VALUES (?,1,?)").bind("खेल प्रतियोगिता में प्रदेश के खिलाड़ियों का शानदार प्रदर्शन",Date.now()+2)]);}
async function mayManage(){const user=await getChatGPTUser();if(!user)return false;return can(await getOrBootstrapRole(user.email,user.displayName),"ब्रेकिंग न्यूज़")}
export async function GET(){await ready();const result=await env.DB.prepare("SELECT id,text,active,created_at AS createdAt FROM breaking_news ORDER BY created_at DESC").all();return Response.json({items:result.results});}
export async function POST(request:Request){if(!await mayManage())return Response.json({error:"Forbidden"},{status:403});await ready();const body=await request.json() as {text?:string};const value=body.text?.trim();if(!value)return Response.json({error:"Headline required"},{status:400});const result=await env.DB.prepare("INSERT INTO breaking_news (text,active,created_at) VALUES (?,1,?) RETURNING id,text,active,created_at AS createdAt").bind(value,Date.now()).first();return Response.json({item:result},{status:201});}
export async function PATCH(request:Request){if(!await mayManage())return Response.json({error:"Forbidden"},{status:403});await ready();const body=await request.json() as {id?:number;text?:string;active?:boolean};if(!body.id)return Response.json({error:"ID required"},{status:400});if(typeof body.active==="boolean")await env.DB.prepare("UPDATE breaking_news SET active=? WHERE id=?").bind(body.active?1:0,body.id).run();if(body.text?.trim())await env.DB.prepare("UPDATE breaking_news SET text=? WHERE id=?").bind(body.text.trim(),body.id).run();return Response.json({ok:true});}
export async function DELETE(request:Request){if(!await mayManage())return Response.json({error:"Forbidden"},{status:403});await ready();const id=Number(new URL(request.url).searchParams.get("id"));if(!id)return Response.json({error:"ID required"},{status:400});await env.DB.prepare("DELETE FROM breaking_news WHERE id=?").bind(id).run();return Response.json({ok:true});}
